# escapeLatexSpecials <- function(x) {
#   x <- gsub("\\&Ast", "", x, fixed = T)
#   x <- gsub("\\&nacute;", "ń", x, fixed = T)
#   x <- gsub("\\&ldquo", "", x, fixed = T)
#   x <- gsub("\\&Rdquo", "", x, fixed = T)
#   x <- gsub("\\'{i}", "í", x, fixed = T)
#   x <- gsub("\\=i", "ī", x, fixed = T)
#   x <- gsub("\\O{E}", "Œ", x, fixed = T)
#   x <- gsub("\\'{e}", "é", x, fixed = T)
#   x <- gsub("\\'{E}", "é", x, fixed = T)
#   x <- gsub("\\~{o}", "õ", x, fixed = T)
#   x <- gsub("\\'{a}", "á", x, fixed = T)
#   x <- gsub("\\c{c}", "ç", x, fixed = T)
#   x <- gsub("\\emph{", "", x, fixed = T)
#   x <- gsub("\\={a}", "ā", x, fixed = T)
#   x <- gsub("\\`A", "à", x, fixed = T)
#   x <- gsub("\\l{}", "ł", x, fixed = T)
#   x <- gsub("\\.{z}", "ż", x, fixed = T)
#   x <- gsub("\\`a", "à", x, fixed = T)
#   x <- gsub("L\\?", "L’", x)
#   x <- gsub("\\?s", "’s", x)
#   x <- gsub("\\'{s}", "ś", x, fixed = T)
#   x <- gsub('\\"{O}', "Ö", x, fixed = T)
#   x <- gsub("\\'{o}", "ó", x, fixed = T)
#   x <- gsub("\\~{n}", "ñ", x, fixed = T)
# 
#   x <- gsub("\\'e", "é", x, fixed = T)
#   x <- gsub("\\^{a}", "â", x, fixed = T)
#   x <- gsub("\\`{e}", "è", x, fixed = T)
#   x <- gsub("\\'{u}", "ú", x, fixed = T)
#   x <- gsub("\\'{U}", "Ú", x, fixed = T)
#   x <- gsub("\\~{a}", "ã", x, fixed = T)
#   x <- gsub('\\"{a}', "ä", x, fixed = T)
#   x <- gsub('\\"{o}', "ö", x, fixed = T)
#   x <- gsub("\\'e", "é", x, fixed = T)
#   x <- gsub("\\'{z}", "ź", x, fixed = T)
#   x <- gsub("\\'z", "ź", x, fixed = T)
#   x <- gsub('\\"{u}', "ü", x, fixed = T)
#   x <- gsub('\\$', "", x, fixed = T)
#   x <- gsub("\\^{e}", "ê", x, fixed = T)
#   x <- gsub("\\~{a}", "ã", x, fixed = T)
#   x <- gsub("\\'{A}", "Á", x, fixed = T)
#   x <- gsub("\\'i", "í", x, fixed = T)
#   x <- gsub("\\&", "", x, fixed = T)
#   x <- gsub("\\'a", "á", x, fixed = T)
#   x <- gsub("\\'o", "ó", x, fixed = T)
#   x <- gsub("\\'I", "í", x, fixed = T)
#   x <- gsub("\\=I", "i", x)
#   x <- gsub("\\^u", "û", x, fixed = T)
#   x <- gsub("\\ku", "ų", x, fixed = T)
#   x <- gsub("\\v{s}", "š", x, fixed = T)
#   x <- gsub("\\k{a}", "ą", x, fixed = T)
# 
#   x <- gsub("\\v{z}", "ž", x, fixed = T)
#   x <- gsub("\\.{e}", "ė", x, fixed = T)
#   x <- gsub("\\={u}", "ū", x, fixed = T)
#     x <- gsub("\\v{c}", "č", x, fixed = T)
# 
#   x <- gsub("\\v{Z}", "ž", x, fixed = T)
#   x <- gsub("\\vs", "š", x, fixed = T)
#   x <- gsub("\\`o", "ò", x, fixed = T)
#     x <- gsub("\\v{r}", "ř", x, fixed = T)
#   x <- gsub("\\ke", "ę", x, fixed = T)
#   x <- gsub("\\o{}", "ø", x, fixed = T)
#   x <- gsub("\\={o}", "ō", x, fixed = T)
#     x <- gsub("\\.{n}", "ṅ", x, fixed = T)
#   x <- gsub("\\=e", "ē", x, fixed = T)
#   x <- gsub("\\'{n}", "ń", x, fixed = T)
#   x <- gsub("\\={i}", "ī", x, fixed = T)
#   x <- gsub("\\=a", "ā", x, fixed = T)
#   x <- gsub("\\.e", "ė", x, fixed = T)
#   x <- gsub("\\k{I}", "į", x, fixed = T)
#   x <- gsub("\\kI", "į", x, fixed = T)
#   x <- gsub("\\v{S}", "š", x, fixed = T)
#   x <- gsub("\\v{e}", "ě", x, fixed = T)
#   x <- gsub("\\^{i}", "î", x, fixed = T)
#   x <- gsub("\\=o", "ō", x, fixed = T)
#   x <- gsub('\\"{i}', "ï", x, fixed = T)
#   x <- gsub("\\~{a}", "ã", x, fixed = T)
#   x <- gsub("\\.{Z}", "ż", x, fixed = T)
#   x <- gsub('\\"u', "ü", x, fixed = T)
#   x <- gsub("\\l", "ł", x, fixed = T)
#   x <- gsub("\\k{e}", "ę", x, fixed = T)
#   x <- gsub("\\'{I}", "Í", x, fixed = T)
#   x <- gsub("\\^{E}", "Ê", x, fixed = T)
#   x <- gsub("\\'{S}", "Ś", x, fixed = T)
#   x <- gsub("\\L{}", "Ł", x, fixed = T)
#   x <- gsub("\\'y", "ý", x, fixed = T)
#   x <- gsub("\\ka", "ą", x, fixed = T)
#   x <- gsub('\\"{U}', "Ü", x, fixed = T)
#   x <- gsub("\\v{C}", "č", x, fixed = T)
#   x <- gsub("\\'n", "ń", x, fixed = T)
#   return(x)
# }

escapeLatexSpecials <- function(x) {
  x <- gsub("\\&Ast", "", x, fixed = T)
  x <- gsub("\\&nacute;", "\u{144}", x, fixed = T)
  x <- gsub("\\&ldquo", "", x, fixed = T)
  x <- gsub("\\&Rdquo", "", x, fixed = T)
  x <- gsub("\\'{i}", "\u{ED}", x, fixed = T)
  x <- gsub("\\=i", "\u{12B}", x, fixed = T)
  x <- gsub("\\O{E}", "\u{152}", x, fixed = T)
  x <- gsub("\\'{e}", "\u{E9}", x, fixed = T)
  x <- gsub("\\'{E}", "\u{E9}", x, fixed = T)
  x <- gsub("\\~{o}", "\u{F5}", x, fixed = T)
  x <- gsub("\\'{a}", "\u{E1}", x, fixed = T)
  x <- gsub("\\c{c}", "\u{E7}", x, fixed = T)
  x <- gsub("emph{", "", x, fixed = T)
  x <- gsub("\\={a}", "\u{101}", x, fixed = T)
  x <- gsub("\\`A", "\u{E0}", x, fixed = T)
  x <- gsub("\\l{}", "\u{142}", x, fixed = T)
  x <- gsub("\\.{z}", "\u{17C}", x, fixed = T)
  x <- gsub("\\`a", "\u{E0}", x, fixed = T)
  x <- gsub("L\\?", "L\u{2019}", x)
  x <- gsub("\\?s", "\u{2019}s", x)
  x <- gsub("\\'{s}", "\u{15B}", x, fixed = T)
  x <- gsub('\\"{O}', "\u{D6}", x, fixed = T)
  x <- gsub("\\'{o}", "\u{F3}", x, fixed = T)
  x <- gsub("\\~{n}", "\u{F1}", x, fixed = T)
  x <- gsub("\\'e", "\u{E9}", x, fixed = T)
  x <- gsub("\\^{a}", "\u{E2}", x, fixed = T)
  x <- gsub("\\`{e}", "\u{E8}", x, fixed = T)
  x <- gsub("\\'{u}", "\u{FA}", x, fixed = T)
  x <- gsub("\\'{U}", "\u{DA}", x, fixed = T)
  x <- gsub("\\~{a}", "\u{E3}", x, fixed = T)
  x <- gsub('\\"{a}', "\u{E4}", x, fixed = T)
  x <- gsub('\\"{o}', "\u{F6}", x, fixed = T)
  x <- gsub("\\'e", "\u{E9}", x, fixed = T)
  x <- gsub("\\'{z}", "\u{17A}", x, fixed = T)
  x <- gsub("\\'z", "\u{17A}", x, fixed = T)
  x <- gsub('\\"{u}', "\u{FC}", x, fixed = T)
  x <- gsub('\\$', "", x, fixed = T)
  x <- gsub("\\^{e}", "\u{EA}", x, fixed = T)
  x <- gsub("\\~{a}", "\u{E3}", x, fixed = T)
  x <- gsub("\\'{A}", "\u{C1}", x, fixed = T)
  x <- gsub("\\'i", "\u{ED}", x, fixed = T)
  x <- gsub("\\&", "", x, fixed = T)
  x <- gsub("\\'a", "\u{E1}", x, fixed = T)
  x <- gsub("\\'o", "\u{F3}", x, fixed = T)
  x <- gsub("\\'I", "\u{ED}", x, fixed = T)
  x <- gsub("\\=I", "i", x)
  x <- gsub("\\^u", "\u{FB}", x, fixed = T)
  x <- gsub("\\ku", "\u{173}", x, fixed = T)
  x <- gsub("\\v{s}", "\u{161}", x, fixed = T)
  x <- gsub("\\k{a}", "\u{105}", x, fixed = T)
  x <- gsub("\\v{z}", "\u{17E}", x, fixed = T)
  x <- gsub("\\.{e}", "\u{117}", x, fixed = T)
  x <- gsub("\\={u}", "\u{16B}", x, fixed = T)
  x <- gsub("\\v{c}", "\u{10D}", x, fixed = T)
  x <- gsub("\\v{Z}", "\u{17E}", x, fixed = T)
  x <- gsub("\\vs", "\u{161}", x, fixed = T)
  x <- gsub("\\`o", "\u{F2}", x, fixed = T)
  x <- gsub("\\v{r}", "\u{159}", x, fixed = T)
  x <- gsub("\\ke", "\u{119}", x, fixed = T)
  x <- gsub("\\o{}", "\u{F8}", x, fixed = T)
  x <- gsub("\\={o}", "\u{14D}", x, fixed = T)
  x <- gsub("\\.{n}", "\u{1E45}", x, fixed = T)
  x <- gsub("\\=e", "\u{113}", x, fixed = T)
  x <- gsub("\\'{n}", "\u{144}", x, fixed = T)
  x <- gsub("\\={i}", "\u{12B}", x, fixed = T)
  x <- gsub("\\=a", "\u{101}", x, fixed = T)
  x <- gsub("\\.e", "\u{117}", x, fixed = T)
  x <- gsub("\\k{I}", "\u{12F}", x, fixed = T)
  x <- gsub("\\kI", "\u{12F}", x, fixed = T)
  x <- gsub("\\v{S}", "\u{161}", x, fixed = T)
  x <- gsub("\\v{e}", "\u{11B}", x, fixed = T)
  x <- gsub("\\^{i}", "\u{EE}", x, fixed = T)
  x <- gsub("\\=o", "\u{14D}", x, fixed = T)
  x <- gsub('\\"{i}', "\u{EF}", x, fixed = T)
  x <- gsub("\\~{a}", "\u{E3}", x, fixed = T)
  x <- gsub("\\.{Z}", "\u{17C}", x, fixed = T)
  x <- gsub('\\"u', "\u{FC}", x, fixed = T)
  x <- gsub("\\l", "\u{142}", x, fixed = T)
  x <- gsub("\\k{e}", "\u{119}", x, fixed = T)
  x <- gsub("\\'{I}", "\u{CD}", x, fixed = T)
  x <- gsub("\\^{E}", "\u{CA}", x, fixed = T)
  x <- gsub("\\'{S}", "\u{15A}", x, fixed = T)
  x <- gsub("\\L{}", "\u{141}", x, fixed = T)
  x <- gsub("\\'y", "\u{FD}", x, fixed = T)
  x <- gsub("\\ka", "\u{105}", x, fixed = T)
  x <- gsub('\\"{U}', "\u{DC}", x, fixed = T)
  x <- gsub("\\v{C}", "\u{10D}", x, fixed = T)
  x <- gsub("\\'n", "\u{144}", x, fixed = T)
  x <- gsub("\\'n", "\u{144}", x, fixed = T)
  x <- gsub("\\c{c}~{a}", "\u{E7}\u{E3}", x, fixed = T)
  
  return(x)
}

# for (i in 1:nrow(bib)){
#   bib[i,"title"] <- enc2utf8(escapeLatexSpecials(bib[i,"TITLE"]))
# }
# bib[,c('TITLE','title')] %>% View()
